from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_round_six_settings_matches_updates_heading_and_removes_timezone_copy():
    markup = (ROOT / "src" / "webui" / "index.html").read_text(encoding="utf-8")
    reference = (ROOT / "src" / "webui" / "reference_acceptance.js").read_text(encoding="utf-8")
    styles = (ROOT / "src" / "webui" / "reference_acceptance.css").read_text(encoding="utf-8")

    assert "Timezone also controls timestamps generated by Nowlert notification formatters." not in markup
    assert "Timezone also controls timestamps generated by Nowlert notification formatters." not in reference
    assert 'regional.querySelectorAll(":scope > .reference-regional-info")' in reference

    round_six = styles[styles.index("/* 2026-09-18 round-six refresh and Settings alignment corrections. */"):]
    assert "grid-template-columns: 38px minmax(0, 1fr) !important;" in round_six
    assert "height: 36px !important;" in round_six
    assert "width: 36px !important;" in round_six
    assert "font-size: 1.08rem !important;" in round_six
    assert "font-size: 0.7rem !important;" in round_six
    assert ".reference-regional-info" in round_six
    assert "display: none !important;" in round_six


def test_round_six_initial_history_uses_single_paged_request_and_hides_construction_footer():
    app = (ROOT / "src" / "webui" / "app.js").read_text(encoding="utf-8")
    patch = (ROOT / "src" / "webui" / "qa_patch.js").read_text(encoding="utf-8")

    assert 'typeof window.nowlertInitialDeliveryRequest === "function"' in app
    assert 'typeof window.nowlertInitialAuditRequest === "function"' in app
    assert 'deliveries: ["Delivery history", initialDeliveryRequest' in app
    assert 'audit: ["Audit log", initialAuditRequest' in app

    assert "function qaFetchDeliveryPage(page)" in patch
    assert "function qaFetchAuditPage(page)" in patch
    assert "window.nowlertInitialDeliveryRequest = () => qaFetchDeliveryPage(qaDeliveryPage);" in patch
    assert "window.nowlertInitialAuditRequest = () => qaFetchAuditPage(qaAuditPage);" in patch
    assert "await Promise.all([qaLoadDeliveryPage(qaDeliveryPage), qaLoadAuditPage(qaAuditPage)])" not in patch

    assert 'className: "audit-footer qa-delivery-footer qa-pagination-footer",' in patch
    assert "hidden: true," in patch
    assert "footer.hidden = false;" in patch


def test_round_six_workspace_cache_hydrates_after_session_and_refreshes_in_background():
    app = (ROOT / "src" / "webui" / "app.js").read_text(encoding="utf-8")
    patch = (ROOT / "src" / "webui" / "qa_patch.js").read_text(encoding="utf-8")

    session_start = app.index('const sessionRequest = request("/session");')
    bootstrap_start = app.index('const status = await request("/bootstrap");')
    restore = app.index("await restoreSession(sessionRequest);")
    assert session_start < bootstrap_start < restore
    assert "void sessionRequest.catch(() => {});" in app
    assert "async function restoreSession(prefetchedSession = null)" in app

    assert 'const QA_WORKSPACE_CACHE_KEY = "nowlert.workspace-cache.v1";' in patch
    assert "const QA_WORKSPACE_CACHE_TTL_MS = 5 * 60 * 1000;" in patch
    assert "function qaSaveWorkspaceCache()" in patch
    assert "function qaHydrateWorkspaceCache(session, { render = true } = {})" in patch
    assert "window.sessionStorage.setItem(" in patch
    assert "window.sessionStorage.getItem(" in patch
    assert "qaHydrateWorkspaceCache(session, { render: false });" in patch
    assert 'window.addEventListener("pagehide", qaSaveWorkspaceCache);' in patch
    assert "qaClearWorkspaceCache();" in patch
